### ISSUE TITLE
code release

### ISSUE THREAD

**Issue by Max-minute** [ywyue/AGILE3D#1]
Hello yuanwen !
I wonder when will the code be released?

**Comment by ywyue** [comment]
Hi, thanks for your interest! We will release the code as soon as the paper acceptance. I will keep you posted!

**Comment by Max-minute** [comment]
Thanks so much for your prompt reply.

> Hi, thanks for your interest! We will release the code as soon as the paper acceptance. I will keep you posted!

**Comment by ywyue** [comment]
Hi @Max-minute, our code has been released now. Hope it is still helpful.

**Comment by Max-minute** [comment]
> Hi @Max-minute, our code has been released now. Hope it is still helpful.

Congratulations on the acceptance of the paper! Thanks for releasing the code！
