### ISSUE TITLE
Are there any methods to obtain 3D masks without interactive clicking?

### ISSUE THREAD

**Issue by hm123450** [ywyue/AGILE3D#11]
Hello, Thank you for great your work very much. It helps me a lot. I would like to ask, if I already have a complete 3D scene graph as well as some processed sparse point clouds for prompts. Can I get the 3dmask without interactive clicking? Also, I want to know is there a limit to the number of point cloud points for prompts? The processed sparse point clouds may be a lot.

**Comment by ywyue** [comment]
Hi @hm123450, thank you for your interest and kind words.

> if I already have a complete 3D scene graph as well as some processed sparse point clouds for prompts. Can I get the 3dmask without interactive clicking? 

Do you know which prompts belong to which object in your 3D scene graph, e.g. the object id of each prompt? If so, it is quite straightforward to assemble the click idx based on this prior knowledge. Please build `click_idx` [here](https://github.com/ywyue/AGILE3D/blob/2aa12f2642116da980c1f9a2f696770a66400c7e/engine.py#L231) based on the prompts you have. For `click_time_idx`, you may try to set it randomly. 

> Also, I want to know is there a limit to the number of point cloud points for prompts? 

The number of prompts depends on two things:
- The memory of your GPU
- We train the network using iterative clicks sampling. We randomly pick up to 10 objects, each object has a maximum of 20 clicks, i.e. the maximum number of clicks (or prompts) the network has seen during training is 200. But I think the network should be  robust to even larger number of clicks. 

I hope that helps and feel free to let me know if there is further concern. I am curious about the results with your prompts :)

**Comment by hm123450** [comment]
> Hi @hm123450, thank you for your interest and kind words.
> 
> > if I already have a complete 3D scene graph as well as some processed sparse point clouds for prompts. Can I get the 3dmask without interactive clicking?
> 
> Do you know which prompts belong to which object in your 3D scene graph, e.g. the object id of each prompt? If so, it is quite straightforward to assemble the click idx based on this prior knowledge. Please build `click_idx` [here](https://github.com/ywyue/AGILE3D/blob/2aa12f2642116da980c1f9a2f696770a66400c7e/engine.py#L231) based on the prompts you have. For `click_time_idx`, you may try to set it randomly.
> 
> > Also, I want to know is there a limit to the number of point cloud points for prompts?
> 
> The number of prompts depends on two things:
> 
> * The memory of your GPU
> * We train the network using iterative clicks sampling. We randomly pick up to 10 objects, each object has a maximum of 20 clicks, i.e. the maximum number of clicks (or prompts) the network has seen during training is 200. But I think the network should be  robust to even larger number of clicks.
> 
> I hope that helps and feel free to let me know if there is further concern. I am curious about the results with your prompts :)

Wow, thank you very much for your quick response. I will try to reduce the number of points.
I see that your code should also support 3D segmentation of a single object.
![image](https://github.com/user-attachments/assets/7da424be-b2e7-42c8-afd1-76c692a820d0)
I only need to perform segmentation on a single object, not multiple ones (for example, I already have some incomplete point cloud data of a chair). In this situation, do I still need an object_id?

**Comment by ywyue** [comment]
Hi @hm123450, single-object segmentation is a special case of multi-object segmentation. In single-object case, there are two kinds of clicks: **negative clicks (object_id=0)** for background and **positive clicks (object_id=1)** for the target object. 

In your case, if you already have some points of a chair, you can use those points as positive clicks (i.e. set the `click_idx` of those points as 1). You don't need to handle background clicks as there are some learned background clicks by default [here](https://github.com/ywyue/AGILE3D/blob/2aa12f2642116da980c1f9a2f696770a66400c7e/models/agile3d.py#L47). This input can already enable the model to produce a segmentation mask for the chair. 

Giving more negative clicks in the background region (if you also have them) should further improve the results although they are not necessary in your case. Best to try out and see what fits your need :)

**Comment by hm123450** [comment]
> Hi @hm123450, single-object segmentation is a special case of multi-object segmentation. In single-object case, there are two kinds of clicks: **negative clicks (object_id=0)** for background and **positive clicks (object_id=1)** for the target object.
> 
> In your case, if you already have some points of a chair, you can use those points as positive clicks (i.e. set the `click_idx` of those points as 1). You don't need to handle background clicks as there are some learned background clicks by default [here](https://github.com/ywyue/AGILE3D/blob/2aa12f2642116da980c1f9a2f696770a66400c7e/models/agile3d.py#L47). This input can already enable the model to produce a segmentation mask for the chair.
> 
> Giving more negative clicks in the background region (if you also have them) should further improve the results although they are not necessary in your case. Best to try out and see what fits your need :)

Thank you so much. You are so friendly and kind. I will try out 2 ways to see what fits most.
