### ISSUE TITLE
OOM memory and how to make this runnable

### ISSUE THREAD

**Issue by dsvilarkovic** [ywyue/AGILE3D#5]
Hey, I am running this on 4060TI (16GB) and looking into how I can downgrade the backend to make this runnable for smaller GPUs in runtime or possibly CPUs. Can you give any tips? Many thanks

**Comment by ywyue** [comment]
Closed as we discussed 1:1 in other apps. I also post the answers here which may be helpful to other readers.

To stay the same setup as ours, I recommend running the training and eval code on GPUs with at least 24GB. For KITTI-360, GPU with larger memory is even required. If you only have GPUs with, for example, 16GB, then it is recommended to 1. reduce batch size, or 2. use a smaller backbone, or 3. increase the `voxel_size`, or 4. crop/downsample the point cloud.

The interactive tool can run on both GPU and CPU. For each setup, please install a separate Python environment. More details in the [instruction](https://github.com/ywyue/AGILE3D/blob/main/demo.md).
