### ISSUE TITLE
Training problem - list index out of range

### ISSUE THREAD

**Issue by AshkanAlami** [ywyue/AGILE3D#6]
Hi,

Firstly, thank you for your amazing work!

I'm having a problem with the training script. When I run it, I get this error:

pos_enc = pos_encodings_pcd[hlevel][0][b]# [num_points, 128]
IndexError: list index out of range

I noticed that the shape of pos_enc is (5, 1, 1). This causes the error with a batch size more than 1 (by default batch size 5). It works fine with a batch size 1.

Do you have any suggestions on how to fix this so it works with a batch size of more than 1?

Thanks!

**Comment by ywyue** [comment]
Hey thanks for your interests! I recently updated the code to make the interactive tool also run on CPU but it seems that it broke the training. I will fix this problem soon.

For a quick solution, could you please revert the code to the previous version: `git reset --hard 843ead4`? It should solve your problem. If not, let me know. Thanks.

**Comment by AshkanAlami** [comment]
Thanks for your quick reply!
The previous version is working, thanks.
