### ISSUE TITLE
Question about web visualizer 

### ISSUE THREAD

**Issue by rpartsey** [ywyue/AGILE3D#7]
Thank you for open-sourcing your work! I found interactive tool interesting to play with!

Have you tried launching the tool on the remote machine and forwarding the display to the local machine's browser? When I uncomment `o3d.visualization.webrtc_server.enable_webrtc()` line commented [here](https://github.com/ywyue/AGILE3D/blob/fcb8444ca2e2bd8270d349874b2e083c78e93b7d/interactive_tool/gui.py#L29C11-L29C58), ssh into remote machine, do port forwarding and access the visualisation in my browser I'm seeing that rendering quality is poor. 

It looks like that when the app is launched from the ssh terminal, rendering falls back to the software rendering, not GPU rendering. But when I connect to the remote machine via TeamViewer and run the app remotely, it uses GPU rendering and browser rendering quality is much better. Have you by any chance tried that? 

Thank you in advance!

**Comment by ywyue** [comment]
Hi @rpartsey , thanks for your interest in our work! 

> Have you tried launching the tool on the remote machine and forwarding the display to the local machine's browser?

Nope. I only tried launching the tool **locally** and forwarding the display to the local machine's browser. In this case, the rendering quality is good (though not as good as the desktop tool). Please note the keyboard events will not work for the browser tool, except for basic commands, e.g. Ctrl and Shift (see this [issue](https://github.com/isl-org/Open3D/issues/5711) of Open3D). This seems a bug that Open3D web server can not forward all the keyboard events. 

> It looks like that when the app is launched from the ssh terminal, rendering falls back to the software rendering, not GPU rendering. But when I connect to the remote machine via TeamViewer and run the app remotely, it uses GPU rendering and browser rendering quality is much better. Have you by any chance tried that?

I am not sure how the GPU rendering works with Open3D. When I want to run the app remotely, I typically connect to the remote machine via TeamViewer, which enables smooth interaction and high-quality display. 

Hope that helps!

**Comment by ywyue** [comment]
Close for now. Feel free to reopen it if you have any further concerns.
