### ISSUE TITLE
The experimental setting of comparison with fully-supervised methods

### ISSUE THREAD

**Issue by panzhiyi** [ywyue/AGILE3D#8]
Fascinating work! However, I had some questions about the experimental setup while reading your article.

When compared with the fully-supervised method Mask3D, how is AGILE3D set up? Does the number of clicks (#clicks) in Table 3 refer to the average number of clicks per object? If so, why is this experiment placed in 4.1 EVALUATION ON **SINGLE**-OBJECT SEGMENTATION?

**Comment by ywyue** [comment]
Hi @panzhiyi , thanks for your interest! Feel free to ask questions.

When compared Mask3D, we evaluate AGILE3D in the single-object segmentation setting. For each object in a scene, we add positive and negative clicks. We then feed the binary segmentation masks of all objects into Mask3D's evaluation protocol to calculate AP. In table 3, for example, #clicks = 1 means each object is given one (positive) click. #clicks = 10 means each object is given 10 clicks.

Hope this helps! Let me know if you have any further concerns.

**Comment by panzhiyi** [comment]
> Hi @panzhiyi , thanks for your interest! Feel free to ask questions.
> 
> When compared Mask3D, we evaluate AGILE3D in the single-object segmentation setting. For each object in a scene, we add positive and negative clicks. We then feed the binary segmentation masks of all objects into Mask3D's evaluation protocol to calculate AP. In table 3, for example, #clicks = 1 means each object is given one (positive) click. #clicks = 10 means each object is given 10 clicks.
> 
> Hope this helps! Let me know if you have any further concerns.

Thanks for your prompt response! One more small question, when training and testing with a multi-object segmentation setup, how is the number of objects set?

**Comment by ywyue** [comment]
Hi @panzhiyi , this is a great question! 

For training, we randomly select 1-10 objects. The code for this step is here: https://github.com/ywyue/AGILE3D/blob/2aa12f2642116da980c1f9a2f696770a66400c7e/engine.py#L65C52-L65C63

For testing, we gave a description on how we select objects for multi-object segmentation setup in section D.2 DATA PREPARATION in the appendix of the paper:

> In practice, it would not be feasible for a user to simultaneously annotate all the objects in a large scene. Motivated by this consideration, we set the maximum number of target objects in each evaluation sample as 10. For each scene, we randomly select M ∈ [1, 2, ..., 10] nearby objects as evaluation samples.

I will try to clean and release the our data preparation code within next month. If you want to check the code immediately, feel free to leave me an email and I will send it to you.

**Comment by panzhiyi** [comment]
Thank you very much for your answer! My issues have been resolved. Here's my email: panzhiyi1996@gmail.com
