### ISSUE TITLE
Visualization Problem

### ISSUE THREAD

**Issue by congwei45** [ywyue/AGILE3D#9]
I use the remote tool mobilexterm remote server. When visualizing, the interactive tool displayed locally is very laggy. How do you run the interactive tool?

**Comment by ywyue** [comment]
Hi @congwei45 , I run the interactive tool directly in my local desktop. The tool is relied on Open3D and there are some known issues for remote access, see: https://github.com/ywyue/AGILE3D/issues/7

**Comment by congwei45** [comment]
How are each subgraph in Figure 4 generated? Where is the code? What visualization tool is used?
